version: '3.9'
services:
  vault:
    image: hashicorp/vault:${VAULT_CE_VERSION}
    restart: always
    container_name: ${VAULT_CONTAINER_NAME}
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
    volumes:
      - ./config:/vault/config
      - ./policies:/vault/policies
      - ../../volumes/vault/data:/vault/data
      - ../../volumes/vault/logs:/vault/logs
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json
    networks:
      - vault

networks:
  vault:
    name: vault-network